import {User} from "../../shared/models/user.model";
export const VENUES_MOCK: Array<string> = [
    'Roma',
    'Ponte Galeria (RM)',
    'Bari',
    'Bologna',
    'Brescia',
    'Cagliari',
    'Caltanissetta',
    'Carpi (MO)',
    'Catanzaro',
    'Ferentino (FR)',
    'Firenze',
    'Fiume Veneto (PN)',
    'Genova',
    'Lancenigo di Villorba (TV)',
    'Melendugno (LE)',
    'Assago (MI)',
    'Pioltello (MI)',
    'Monteriggioni (SI)',
    'Napoli',
    'Torre Annunziata (NA)',
    'Orvieto (TR)',
    'Osimo (AN)',
    'Padova',
    'Palermo',
    'Pont Saint Martin (AO)',
    'Porto San Giorgio (FM)',
    'Rimini',
    'Taranto',
    'Mosciano Sant’Angelo (TE)',
    'Tortoreto (TE)',
    'Torino',
    'Tremestieri Etneo (CT)',
    'Povo (TN)',
    'Trento',
    'Treviolo (BG)',
    'Udine',
    'ESTERA',
    'ALTRO'
];

export const USERS_MOCK: User[] = [
    new User('Fabio', 'Siliberto', 'fabio.siliberto@eng.it', 'password1', 'Ponte Galeria (RM)', 1),
    new User('Alessandro', 'Avolio', 'alessandro.avolio@eng.it', 'password2', 'Ponte Galeria (RM)', 2),
    new User('Umberto', 'Tarantino', 'umberto.tarantino@eng.it', 'password3', 'Ponte Galeria (RM)', 3),
];